env:
  global:
    - CC_TEST_REPORTER_ID=eafb5edb64be8870346e629f6272cb6490c45adb8a7ecef220bfa8a000e6e385
language: python
python: 3.8

before_install:
  - pip install poetry

install:
  - make install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make lint
  - make test-coverage

after script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
